// Liste des mots Motpsy
// Format : [mot, définition, catégorie, photo (Oui/Non)]
// Catégories : Classique, Composé, VO, VIP

const LISTE_MOTS_A_TROUVER = [
  [`ANGOISSE`, `Une notion intimement liée à l'histoire de la psychanalyse (et de l'humanité !). Freud l'a d'abord définie comme un résultat, avant de la mettre à l'origine du refoulement (1926). Mélanie Klein en a fait un concept clef de sa pratique "l'interprétation doit porter sur le point d'angoisse maximal" (F. Palasio Espasa, Dictionnaire international de la psychanalyse, 2002) Un "mini" podcast sur le sujet :  https://www.radiofrance.fr/franceinter/podcasts/les-mots-du-psy/l-angoisse-1226041`, `Classique`, `Non`],
  [`DÉNI`, `Un prof avait pour habitude de dire parlant des pervers "Oui, je sais, mais...".  E. Roudinesco et M. Plon dans le dictionnaire de la psychanalyse (La Pochothèque, 2011)"...Freud le définit comme un mécanisme pervers par lequel le sujet fait coexister 2 réalités contradictoires : le refus et la reconnaissance de l'absence de pénis chez la femme". Elles coexistent de manière clivée, sans unification possible.  L'actualité quotidienne fournit fréquemment des exemples de déni.`, `Classique`, `Non`],
  [`DÉFENSE`, `Terme apparu dès 1894 chez Freud et enrichi plusieurs fois au cours de ses écrits. Anna F. a beaucoup développé cette notion. Terme suscitant de grands débats théoriques, on peut citer parmi les mécanismes de défense : déni, condensation, projection…`, `Classique`, `Non`],
  [`PRÉOEDIPIEN`, `"...période de développement psychosexuel, antérieure à l'instauration du complexe d'Œdipe ; dans cette période prédomine, pour les deux sexes, l'attachement à la mère" (Laplanche et Pontalis, vocabulaire de la psychanalyse).`, `Classique`, `Non`],
  [`PHALLIQUE`, `Souvent associé pour qualifier un stade de développement, une mère ou une femme. "Si le couple central de l'organisation de la conflictualité de l'analité est, comme nous l'avons vu, le couple actif/passif, le couple central de l'organisation phallique est le couple voyeuriste/exhibitionniste." (Manuel de Psychologie et de psychopathologie clinique généalre, 2ème édition, René Roussillon).`, `Classique`, `Non`],
  [`AUTO-ANALYSE`, `Freud l'a inventée et en a compris les limites. Didier Anzieu dans le dictionnaire international de la psychanalyse "L'autonalayse peut être féconde si elle prolonge un travail psychanalytique auquel elle fait écho". Toujours dans le même article, on apprend que Beckett était analysé par Bion !`, `Composé`, `Non`],
  [`W-FLIESS`, `1858-1928. ORL de sa spécialité, il a mis au point tout un corpus théorico-mystique autour du "bi" avec bien sur un aspect sexuel. Cette deuxième "bromance" de Freud a fini par une brouille en 1906. Si Freud a brulé toutes les lettres de Fliess, Fliess, lui, avait gardé toutes les lettres de Freud. Merci Wilhelm !`, `VIP`, `Oui`],
  [`FÉTICHISME`, `Tout un monde ! En lien avec la perversion, le déni…Le fétiche permet de gommer la différence des sexes. Il permet le comme si en étant investi de manière hypersexuelle. A lire dans les perversions, les chemins de traverse (éditions Tchou), la psychanalyse d'un fétichiste par B. Joseph : "...fantasmes dans lesquels il s'introduisait dans un vêtement de caoutchouc"`, `Classique`, `Non`],
  [`PRÉCONSCIENT`, `un participant majeur de la première topique de Freud. Ce n'est ni le conscient, ni l'inconscient. Pour faire le lien avec les processus de symbolisation, c'est un lieu rempli des représentations choses qui ont franchi la censure. Des mots pourront être mis sur ces représentations, c'est le processus de symbolisation secondaire cher à René Roussillon.`, `Classique`, `Non`],
  [`SÉDUCTION`, `La théorie de la séduction a été abandonnée en 1897 par Freud, suite, notamment, aux échanges avec Fliess. Ce terme ouvre toute la question du fantasme et du trauma, de leur possible co-existence, et de la difficulté supplémentaire que génère la différence générationnelle en situation de séduction...A lire l'artcile sur le sujet dans le Dictionnaire de la psychanalyse d'E. Roudinesco et M. Plon.`, `Classique`, `Non`],
  [`ETAYAGE`, `Le couple mère-bébé en prenant du plaisir dans les moments de nourrissage du bébé fournit un exemple d'étayge de la pulsion sexuelle (de plaisir) à une pulsion d'auto-conservation (besoin de se nourrir). Cela renvoie aussi fondamentalement à l'idée que notre "humanité" n'existe que par tricotage avec nos aînés.`, `Classique`, `Non`],
  [`LIBIDO`, `En latin cela veut dire désir.  Sujet en lien avec les notions de pulsion, sexualité...Quand Laplanche et Pontalis disent qu'il est difficile de donner une définition satisfaisante du terme, cela laisse deviner l'ampleur du sujet…Jung a élargi la notion pour en désigner l'énergie psychique en général.`, `Classique`, `Non`],
  [`ABWHER`, `Défense ! Cf Motpsy N°3.  Laplanche et Pontalis (Vocabulaire de la psychanalyse) "marquée et infiltrée par ce sur quoi elle porte en dernier ressort - la pulsion - la défense prend souvent une allure compulsive et opère au moins partiellement de façon inconsciente"`, `VO`, `Non`],
  [`LE-PETIT-HANS`, `l'article de Freud "Analyse de la phobie d'un garçon de cinq ans (le petit Hans)" parait en 1909. Premier cas d'analyse d'enfants qui montre toute la richesse d'une vie psychique d'enfants.`, `VIP`, `Oui`],
  [`DÉNÉGATION`, `Alors que le déni est plutôt du côté de la psychose, la dénégation fait partie des mécanismes de défense névrotiques. Pourquoi ? Dans la dénégation, la réalité vient à la conscience mais le sujet ne la reconnait pas comme sienne "Cette femme dont j'ai rêvé, non, ce n'est pas ma mère"`, `Classique`, `Non`],
  [`MORCELLEMENT`, `Parmi les angoisses primitives, elle suppose un début`, `Classique`, `Non`],
  [`RÉPÉTITION`, `À compléter`, `Classique`, `Non`],
  [`EMPRISE`, `À compléter`, `Classique`, `Non`],
  [`PROJECTION`, `À compléter`, `Classique`, `Non`],
  [`OBJET-A`, `À compléter`, `Composé`, `Non`],
  [`M-KLEIN`, `À compléter`, `VIP`, `Oui`],
  [`MÉTAPSYCHOLOGIE`, `À compléter`, `Classique`, `Non`],
  [`INTROJECTÉE`, `À compléter`, `Classique`, `Non`],
  [`INTRICATION`, `À compléter`, `Classique`, `Non`],
  [`CONTRE-TRANSFERT`, `À compléter`, `Composé`, `Non`],
  [`RATIONALISATION`, `À compléter`, `Classique`, `Non`],
  [`OBJELKTLIBIDO`, `À compléter`, `VO`, `Non`],
  [`W-R-BION`, `À compléter`, `VIP`, `Oui`],
  [`EROS`, `À compléter`, `Classique`, `Non`],
  [`SYMBOLISATION`, `À compléter`, `Classique`, `Non`],
  [`SURINVESTISSEMENT`, `À compléter`, `Classique`, `Non`],
  [`SUPERVISION`, `À compléter`, `Classique`, `Non`],
  [`SURMOI`, `À compléter`, `Classique`, `Non`],
  [`SQUIGGLE`, `À compléter`, `Classique`, `Non`],
  [`L-ANDRÉAS-SALOMÉ`, `À compléter`, `VIP`, `Oui`],
  [`MOI`, `À compléter`, `Classique`, `Non`],
  [`HYSTÉRIE`, `À compléter`, `Classique`, `Non`],
  [`MASOCHISME`, `À compléter`, `Classique`, `Non`],
  [`THANATOS`, `À compléter`, `Classique`, `Non`],
  [`TRANSFERT`, `À compléter`, `Classique`, `Non`],
  [`ASSOCIATION-LIBRE`, `À compléter`, `Composé`, `Non`],
  [`H-RORSCHACH`, `À compléter`, `VIP`, `Oui`],
  [`MATERNAGE`, `À compléter`, `Classique`, `Non`],
  [`SURMOI`, `À compléter`, `Classique`, `Non`],
  [`AGONIE`, `À compléter`, `Classique`, `Non`],
  [`FIXATION`, `À compléter`, `Classique`, `Non`],
  [`AGONIE`, `À compléter`, `Classique`, `Non`],
  [`NEUROTICA`, `À compléter`, `VO`, `Non`],
  [`A-FREUD`, `À compléter`, `VIP`, `Oui`],
  [`ÇA`, `À compléter`, `Classique`, `Non`],
  [`PSYCHOTIQUES`, `À compléter`, `Classique`, `Non`],
  [`NÉVROSES`, `À compléter`, `Classique`, `Non`],
  [`IMAGINAIRE`, `À compléter`, `Classique`, `Non`],
  [`CLIVAGE`, `À compléter`, `Classique`, `Non`],
  [`IDENTIFICATION-PROJECTIVE`, `À compléter`, `Composé`, `Non`],
  [`R-DIATKINE`, `À compléter`, `VIP`, `Oui`],
];