// Liste des mots Motpsy
// Format : [mot, définition, catégorie, photo, cacher1ereLettre, date, indice, exemple, rebonds]
// Catégories : Classique, VO, VIP, Lacan  (le tiret est détecté automatiquement)
// La date (YYYY-MM-DD) détermine le jour de diffusion. Fallback aléatoire si aucune date ne correspond.
// L'indice (si présent) fait apparaître le bouton 💡 ; vide = pas de bouton.

const LISTE_MOTS_A_TROUVER = [
  [`REFOULEMENT`, `Processus par lequel le sujet repousse et maintient dans l'inconscient des représentations liées à une pulsion.`, `Classique`, ``, false, `2026-08-01`, ``],
  [`PULSION`, `Poussée énergétique d'origine corporelle orientant le sujet vers un but ; charnière entre le somatique et le psychique.`, `Classique`, ``, true, `2026-08-02`, ``],
  [`FREUD`, `Sigmund Freud (1856-1939), neurologue autrichien, fondateur de la psychanalyse.`, `VIP`, ``, false, `2026-08-03`, ``],
  [`SECHEHAYE`, `Marguerite Sechehaye (1887-1964), psychanalyste suisse, théoricienne de la « réalisation symbolique ».`, `VIP`, ``, false, `2026-08-04`, ``],
  [`ANGST`, `« Angoisse » en allemand, notion centrale de la pensée freudienne comme de l'existentialisme.`, `VO`, ``, false, `2026-08-05`, ``],
  [`JOUISSANCE`, `Chez Lacan, satisfaction paradoxale située au-delà du principe de plaisir, mêlée de souffrance.`, `Lacan`, ``, false, `2026-08-06`, ``],
  [`MOI-IDEAL`, `Instance idéale héritée du narcissisme primaire, modèle de toute-puissance (à distinguer de l'idéal du moi).`, `Classique`, ``, false, `2026-08-07`, ``],
  [`STADE-DU-MIROIR`, `Moment où l'enfant s'identifie à sa propre image et constitue son moi par anticipation (Lacan, 1949).`, `Lacan`, ``, false, `2026-08-08`, ``],
  [`SUBLIMATION`, `Dérivation de la pulsion vers un but non sexuel socialement valorisé : art, recherche, création.`, `Classique`, ``, false, `2026-08-09`, `Quand la pulsion se met au service de l'art ou du savoir…`],
  [`JUNG`, `Carl Gustav Jung (1875-1961), psychiatre suisse, fondateur de la psychologie analytique.`, `VIP`, ``, true, `2026-08-10`, ``],
  [`ANGOISSE`, `Une notion intimement liée à l'histoire de la psychanalyse (et de l'humanité !). Freud l'a d'abord définie comme un résultat, avant de la mettre à l'origine du refoulement (1926). Mélanie Klein en a fait un concept clef de sa pratique "l'interprétation doit porter sur le point d'angoisse maximal" (F. Palasio Espasa, Dictionnaire international de la psychanalyse, 2002)`, `Classique`, ``, false, `2026-06-18`, `Sentiment pénible d'attente d'un danger imprécis.`, ``, `https://www.radiofrance.fr/franceinter/podcasts/les-mots-du-psy/l-angoisse-1226041`],
  [`DENI`, `Un prof avait pour habitude de dire parlant des pervers "Oui, je sais, mais...". 
E. Roudinesco et M. Plon dans le dictionnaire de la psychanalyse (La Pochothèque, 2011)"...Freud le définit comme un mécanisme pervers par lequel le sujet fait coexister 2 réalités contradictoires : le refus et la reconnaissance de l'absence de pénis chez la femme". Elles coexistent de manière clivée, sans unification possible. 
L'actualité quotidienne fournit fréquemment des exemples de déni.`, `Classique`, ``, false, `2025-04-01`, ``],
  [`DEFENSE`, `Terme apparu dès 1894 chez Freud et enrichi plusieurs fois au cours de ses écrits. Anna F. a beaucoup développé cette notion. Terme suscitant de grands débats théoriques, on peut citer parmi les mécanismes de défense : déni, condensation, projection…`, `Classique`, ``, false, `2025-04-02`, ``],
  [`PREOEDIPIEN`, `"...période de développement psychosexuel, antérieure à l'instauration du complexe d'Œdipe ; dans cette période prédomine, pour les deux sexes, l'attachement à la mère" (Laplanche et Pontalis, vocabulaire de la psychanalyse).`, `Classique`, ``, false, `2025-04-03`, ``],
  [`PHALLIQUE`, `Souvent associé pour qualifier un stade de développement, une mère ou une femme. "Si le couple central de l'organisation de la conflictualité de l'analité est, comme nous l'avons vu, le couple actif/passif, le couple central de l'organisation phallique est le couple voyeuriste/exhibitionniste." (Manuel de Psychologie et de psychopathologie clinique généalre, 2ème édition, René Roussillon).`, `Classique`, ``, false, `2025-04-04`, ``],
  [`AUTO-ANALYSE`, `Freud l'a inventée et en a compris les limites. Didier Anzieu dans le dictionnaire international de la psychanalyse "L'autonalayse peut être féconde si elle prolonge un travail psychanalytique auquel elle fait écho". Toujours dans le même article, on apprend que Beckett était analysé par Bion !`, `Classique`, ``, false, `2025-04-05`, ``],
  [`FLIESS`, `1858-1928. ORL de sa spécialité, il a mis au point tout un corpus théorico-mystique autour du "bi" avec bien sur un aspect sexuel. Cette deuxième "bromance" de Freud a fini par une brouille en 1906. Si Freud a brulé toutes les lettres de Fliess, Fliess, lui, avait gardé toutes les lettres de Freud. Merci Wilhelm !`, `VIP`, ``, false, `2025-04-06`, ``],
  [`FETICHISME`, `Tout un monde ! En lien avec la perversion, le déni…Le fétiche permet de gommer la différence des sexes. Il permet le comme si en étant investi de manière hypersexuelle. A lire dans les perversions, les chemins de traverse (éditions Tchou), la psychanalyse d'un fétichiste par B. Joseph : "...fantasmes dans lesquels il s'introduisait dans un vêtement de caoutchouc"`, `Classique`, ``, false, `2025-04-07`, ``],
  [`PRECONSCIENT`, `un participant majeur de la première topique de Freud. Ce n'est ni le conscient, ni l'inconscient. Pour faire le lien avec les processus de symbolisation, c'est un lieu rempli des représentations choses qui ont franchi la censure. Des mots pourront être mis sur ces représentations, c'est le processus de symbolisation secondaire cher à René Roussillon.`, `Classique`, ``, false, `2025-04-08`, ``],
  [`SEDUCTION`, `La théorie de la séduction a été abandonnée en 1897 par Freud, suite, notamment, aux échanges avec Fliess. Ce terme ouvre toute la question du fantasme et du trauma, de leur possible co-existence, et de la difficulté supplémentaire que génère la différence générationnelle en situation de séduction...A lire l'artcile sur le sujet dans le Dictionnaire de la psychanalyse d'E. Roudinesco et M. Plon.`, `Classique`, ``, false, `2025-04-09`, ``],
  [`ETAYAGE`, `Le couple mère-bébé en prenant du plaisir dans les moments de nourrissage du bébé fournit un exemple d'étayge de la pulsion sexuelle (de plaisir) à une pulsion d'auto-conservation (besoin de se nourrir). Cela renvoie aussi fondamentalement à l'idée que notre "humanité" n'existe que par tricotage avec nos aînés.`, `Classique`, ``, false, `2025-04-10`, ``],
  [`LIBIDO`, `En latin cela veut dire désir.  Sujet en lien avec les notions de pulsion, sexualité...Quand Laplanche et Pontalis disent qu'il est difficile de donner une définition satisfaisante du terme, cela laisse deviner l'ampleur du sujet…Jung a élargi la notion pour en désigner l'énergie psychique en général.`, `Classique`, ``, false, `2026-06-20`, `Énergie de la pulsion sexuelle (en latin : désir).`],
  [`ABWEHR`, `Défense ! Cf Motpsy N°3.  Laplanche et Pontalis (Vocabulaire de la psychanalyse) "marquée et infiltrée par ce sur quoi elle porte en dernier ressort - la pulsion - la défense prend souvent une allure compulsive et opère au moins partiellement de façon inconsciente"`, `VO`, ``, false, `2025-04-12`, ``],
  [`PETIT-HANS`, `l'article de Freud "Analyse de la phobie d'un garçon de cinq ans (le petit Hans)" parait en 1909. Premier cas d'analyse d'enfants qui montre toute la richesse d'une vie psychique d'enfants.`, `VIP`, ``, false, `2025-04-13`, ``],
  [`DENEGATION`, `Alors que le déni est plutôt du côté de la psychose, la dénégation fait partie des mécanismes de défense névrotiques. Pourquoi ? Dans la dénégation, la réalité vient à la conscience mais le sujet ne la reconnait pas comme sienne "Cette femme dont j'ai rêvé, non, ce n'est pas ma mère"`, `Classique`, ``, false, `2025-04-14`, ``],
  [`MORCELLEMENT`, `Parmi les angoisses primitives, elle suppose un début`, `Classique`, ``, false, `2025-04-15`, ``],
  [`REPETITION`, `*`, `Classique`, ``, false, `2025-04-16`, ``],
  [`EMPRISE`, `À compléter`, `Classique`, ``, false, `2025-04-17`, ``],
  [`PROJECTION`, `À compléter`, `Classique`, ``, false, `2025-04-18`, ``],
  [`OBJET-A`, `À compléter`, `Classique`, ``, false, `2025-04-19`, ``],
  [`KLEIN`, `À compléter`, `VIP`, ``, false, `2025-04-20`, ``],
  [`METAPSYCHOLOGIE`, `À compléter`, `Classique`, ``, false, `2026-11-15`, ``],
  [`INTROJECTEE`, `À compléter`, `Classique`, ``, false, `2025-04-22`, ``],
  [`INTRICATION`, `À compléter`, `Classique`, ``, false, `2025-04-23`, ``],
  [`CONTRE-TRANSFERT`, `À compléter`, `Classique`, ``, false, `2026-06-19`, `Ce que l'analyste ressent en réponse à son patient.`],
  [`RATIONALISATION`, `À compléter`, `Classique`, ``, false, `2025-04-25`, ``],
  [`OBJEKTLIBIDO`, `À compléter`, `VO`, ``, false, `2025-04-26`, ``],
  [`BION`, `À compléter`, `VIP`, ``, false, `2025-04-27`, ``],
  [`EROS`, `À compléter`, `Classique`, ``, false, `2025-04-28`, ``],
  [`SYMBOLISATION`, `À compléter`, `Classique`, ``, false, `2025-04-29`, ``],
  [`SURINVESTISSEMENT`, `À compléter`, `Classique`, ``, false, `2025-04-30`, ``],
  [`SUPERVISION`, `À compléter`, `Classique`, ``, false, `2025-05-01`, ``],
  [`SURMOI`, `À compléter`, `Classique`, ``, false, `2025-05-02`, ``],
  [`SQUIGGLE`, `À compléter`, `Classique`, ``, false, `2025-05-03`, ``],
  [`ANDREAS-SALOME`, `À compléter`, `VIP`, ``, false, `2025-05-04`, ``],
  [`MOI`, `À compléter`, `Classique`, ``, false, `2025-05-05`, ``],
  [`HYSTERIE`, `À compléter`, `Classique`, ``, false, `2025-05-06`, ``],
  [`MASOCHISME`, `À compléter`, `Classique`, ``, false, `2025-05-07`, ``],
  [`THANATOS`, `À compléter`, `Classique`, ``, false, `2025-05-08`, ``],
  [`TRANSFERT`, `À compléter`, `Classique`, ``, false, `2026-06-21`, `Report sur l'analyste de sentiments issus du passé.`],
  [`ASSOCIATION-LIBRE`, `À compléter`, `Classique`, ``, false, `2025-05-10`, ``],
  [`RORSCHACH`, `À compléter`, `VIP`, ``, false, `2025-05-11`, ``],
  [`MATERNAGE`, `À compléter`, `Classique`, ``, false, `2025-05-12`, ``],
  [`AGONIE`, `À compléter`, `Classique`, ``, false, `2025-05-14`, ``],
  [`FIXATION`, `À compléter`, `Classique`, ``, false, `2025-05-15`, ``],
  [`NEUROTICA`, `À compléter`, `VO`, ``, false, `2025-05-17`, ``],
  [`FREUD`, `À compléter`, `VIP`, ``, false, `2025-05-18`, ``],
  [`CA`, `À compléter`, `Classique`, ``, false, `2025-05-19`, ``],
  [`PSYCHOTIQUES`, `À compléter`, `Classique`, ``, false, `2025-05-20`, ``],
  [`NEVROSES`, `À compléter`, `Classique`, ``, false, `2025-05-21`, ``],
  [`IMAGINAIRE`, `À compléter`, `Classique`, ``, false, `2025-05-22`, ``],
  [`CLIVAGE`, `À compléter`, `Classique`, ``, false, `2025-05-23`, ``],
  [`IDENTIFICATION-PROJECTIVE`, `À compléter`, `Classique`, ``, false, `2025-05-24`, ``],
  [`DIATKINE`, `À compléter`, `VIP`, ``, false, `2025-05-25`, ``],
];
